### ISSUE TITLE
xchain-bsc: BSCSCAN_API_KEY not working!

### ISSUE THREAD

**Issue by AminAzGol** [xchainjs/xchainjs-lib#1213]
Calling the `estimateGasPrices()` cause an error while I've already set BSCSCAN_API_KEY

```js

import {BSCChain, Client, defaultBscParams} from "@xchainjs/xchain-bsc"

process.env.BSCSCAN_API_KEY = 'the_api_key'
defaultBscParams.phrase = 'the_phrase'
const bscClient = new Client(defaultBscParams)

const fees = await bscClient.estimateGasPrices()
console.log(fees)

```

expected behaviour:

```
{
  average: {
    type: 'BASE',
    amount: [Function: amount],
    plus: [Function: plus],
    minus: [Function: minus],
    times: [Function: times],
    div: [Function: div],
    lt: [Function: lt],
    lte: [Function: lte],
    gt: [Function: gt],
    gte: [Function: gte],
    eq: [Function: eq],
    decimal: 18
  },
  fast: {
    type: 'BASE',
    amount: [Function: amount],
    plus: [Function: plus],
    minus: [Function: minus],
    times: [Function: times],
    div: [Function: div],
    lt: [Function: lt],
    lte: [Function: lte],
    gt: [Function: gt],
    gte: [Function: gte],
    eq: [Function: eq],
    decimal: 18
  },
  fastest: {
    type: 'BASE',
    amount: [Function: amount],
    plus: [Function: plus],
    minus: [Function: minus],
    times: [Function: times],
    div: [Function: div],
    lt: [Function: lt],
    lte: [Function: lte],
    gt: [Function: gt],
    gte: [Function: gte],
    eq: [Function: eq],
    decimal: 18
  }
}
```

current behavior: 
```
Error: Can not retrieve gasOracle: Max rate limit reached, please use API Key for higher rate limit
    at /home/amin/Projects/Amin/respect-arb/node_modules/@xchainjs/xchain-evm-providers/lib/index.js:392:15
    at Generator.next (<anonymous>)
    at fulfilled (/home/amin/Projects/Amin/respect-arb/node_modules/@xchainjs/xchain-evm-providers/lib/index.js:32:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Can not round robin over GetFeeRates: Error: No provider available to getFeeRates

```

**Comment by AminAzGol** [comment]
as a temporary work around I've come up with this:
```js
import {BSCChain, Client, defaultBscParams} from "@xchainjs/xchain-bsc"

const bscApiKey = 'the_api_key'

/* change the mainnet EtherProvider with a new one and pass APIKey to it's constructor */
defaultBscParams.dataProviders[0].mainnet = new EtherscanProvider(defaultBscParams.providers.mainnet,
            'https://api.bscscan.com',
            bscApiKey,
            BSCChain,
            defaultBscParams.gasAsset,
            defaultBscParams.gasAssetDecimals
        )
defaultBscParams.phrase = phrase
const bscClient = new Client(defaultBscParams)

const fees = await bscClient.estimateGasPrices()
console.log(fees)

```

and it works!

**Comment by 0xp3gasus** [comment]
First things first, I'm not really a fan of XChainJS is using the environment vars, and the temporary approach you have come up is the one I recommend to use when using custom API keys.

On the other hand, you have the bug because the providers of the defaultBscParams are instantiated before you set the `BSCSCAN_API_KEY`, so when you make the API calls the API Key the provider uses inside is undefined

**Comment by AminAzGol** [comment]
Thank you for your response. You're right, by just moving the `process.env.BSCSCAN_API_KEY = 'the_api_key'` above the `import defaultBscParams` the bug is fixed and works fine. 
```js
process.env.BSCSCAN_API_KEY = 'the_api_key'

import {Client, defaultBscParams} from "@xchainjs/xchain-bsc"

defaultBscParams.phrase = 'the_phrase'
const bscClient = new Client(defaultBscParams)

const fees = await bscClient.estimateGasPrices()
console.log(fees)
```
In my mind, I expected defaultBscParams to be a constant (as the name suggests) and not to change based on the environment. Instead, any changes should occur during the instantiation step with `new Client()`.

Like you, I don't prefer using environment variables either, and I believe an injection approach is generally more flexible.
