### ISSUE TITLE
ADD:  support nodejs

### ISSUE THREAD

**Issue by mikewyszinski** [xchainjs/xchainjs-lib#321]
xchainjs fails when running server-side (in node js) 

```
Error: Secure random number generation is not supported by this browser.
Use Chrome, Firefox or Internet Explorer 11
    at oldBrowser (/Users/grim/source/test/node_modules/@xchainjs/xchain-crypto/lib/index.js:6620:9)
    at generateMnemonic (/Users/grim/source/test/node_modules/@xchainjs/xchain-crypto/lib/index.js:25389:30)
    at generatePhrase (/Users/grim/source/test/node_modules/@xchainjs/xchain-crypto/lib/index.js:60007:18)
    at file:///Users/grim/source/test/index.js:3:16
```

I suspect it would be useful if the lib supported both browser and nodejs envs fo anyone wanting to build arbitration bots etc

**Comment by mikewyszinski** [comment]
thanks @angerboy willreview this in the next few days
