### ISSUE TITLE
@xchainjs/xchain-thorchain Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './x/auth' is not defined by "exports

### ISSUE THREAD

**Issue by scovic** [xchainjs/xchainjs-lib#439]
I'm getting this error when trying to require something from `@xchainjs/xchain-thorchain`
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './x/auth' is not defined by "exports" in /home/stefan/Desktop/crypto-test/thor-test/node_modules/cosmos-client/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:299:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:522:3)
    at resolveExports (internal/modules/cjs/loader.js:424:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:464:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/stefan/Desktop/crypto-test/thor-test/node_modules/@xchainjs/xchain-cosmos/lib/index.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```
Any solution?

**Comment by scovic** [comment]
It was bad versions of comsos-client, if anyone has this problem, try installing cosmos-client@0.39.2
